workflows:
  ios_build:
    name: iOS Build (Debug, no codesign)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter clean + pub get
        script: |
          flutter clean
          flutter pub get

      - name: Pod install limpio
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS Debug sin firma
        script: |
          flutter build ios --debug --no-codesign

    artifacts:
      - build/ios/iphoneos/**/*.app
      - build/ios/ipa/*.ipa
