name: BeatNow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  flutter_lints: ^6.0.0
  path_provider: ^2.0.2
  carousel_slider: ^5.1.1
  http: ^1.2.1
  audioplayers: ^6.0.0
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.1.5
  shared_preferences: ^2.2.3
  speech_to_text: ^7.3.0
  cached_network_image: ^3.0.0
  flutter_soloud: ^3.4.5
  google_fonts: ^6.3.2
  regexed_validator: ^2.0.0+1
  pin_code_fields: ^8.0.1
  share_plus: ^12.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/profile.jpg
