// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZFkyvDeMj5NQ3lYTc_NWk2UDHPA2EB8w',
    appId: '1:749315745117:web:0ce591083803a14b0d34b4',
    messagingSenderId: '749315745117',
    projectId: 'auth-2f686',
    authDomain: 'auth-2f686.firebaseapp.com',
    storageBucket: 'auth-2f686.appspot.com',
    measurementId: 'G-DYFRKHSCN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYxlMdQpV2C69Tpd4BRW3YMmwQ-Y4cLZI',
    appId: '1:999819554533:android:636717cb680135e58a2e0c',
    messagingSenderId: '999819554533',
    projectId: 'beatnow-f18e9',
    storageBucket: 'beatnow-f18e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfcD3ltEfrhgMwDRIIaRGrZYigRcE7k4g',
    appId: '1:999819554533:ios:b37ccf3d6168825c8a2e0c',
    messagingSenderId: '999819554533',
    projectId: 'beatnow-f18e9',
    storageBucket: 'beatnow-f18e9.firebasestorage.app',
    iosBundleId: 'app.beatnow.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNWyMQlXtUbDtPxv0G6mi9hrWHWANhmW8',
    appId: '1:749315745117:ios:da9d82da05d994b40d34b4',
    messagingSenderId: '749315745117',
    projectId: 'auth-2f686',
    storageBucket: 'auth-2f686.appspot.com',
    iosClientId: '749315745117-hu5euib4rssck8441e16t3a6sl0ii7m2.apps.googleusercontent.com',
    iosBundleId: 'app.beatnow.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZFkyvDeMj5NQ3lYTc_NWk2UDHPA2EB8w',
    appId: '1:749315745117:web:339b59a29c5595e20d34b4',
    messagingSenderId: '749315745117',
    projectId: 'auth-2f686',
    authDomain: 'auth-2f686.firebaseapp.com',
    storageBucket: 'auth-2f686.appspot.com',
    measurementId: 'G-X7B52H1GRX',
  );
}
